const productos = [
{
    id: 1,
    nombre: "Yeezy DarkSouls",
    precio: 185,
    img: "./img/shoes-souls.jpg",
    cantidad: 1,
},
{
    id: 2,
    nombre: "T-shirt DarkSouls",
    precio: 35,
    img: "./img/ropa-1.jpg",
    cantidad: 1,
},
{
    id: 3,
    nombre: "Hoodie DarkSouls",
    precio: 75,
    img: "./img/ropa-3.jpg",
    cantidad: 1,
},
{
    id: 4,
    nombre: "Hoodie Sekiro",
    precio: 75,
    img: "./img/ropa-3.jpg",
    cantidad: 1,
},
{
    id: 5,
    nombre: "Hoodie Solaire",
    precio: 75,
    img: "./img/ropa-2.jpg",
    cantidad: 1,
},
{
    id: 6,
    nombre: "Figure Solaire of Astora",
    precio: 150,
    img: "./img/figure-2.jpg",
    cantidad: 1,
},
{
    id: 7,
    nombre: "Figure Dark Souls",
    precio: 150,
    img: "./img/figure-1.jpg",
    cantidad: 1,
},
{
    id: 8,
    nombre: "Figure Bloodborne",
    precio: 150,
    img: "./img/figure-3.jpg",
    cantidad: 1,
},
{
    id: 9,
    nombre: "Figure Sekiro",
    precio: 150,
    img: "./img/figure-4.jpg",
    cantidad: 1,
},
];
